### ISSUE TITLE
TV 시리즈 정보 못불러오고 있습니다.

### ISSUE THREAD

**Issue by bgs2313** [wonipapa/DaumMovieTVSeries.bundle#10]
TV 시리즈 정보를 못불러 오고있습니다.
겟 잇 뷰티 시즌 13[2019]가 추가 되어 스캔은되서 클릭하여도 정보를 하나도 불러오지 못하고 있네요
선을 넘는 녀석들도 시즌 2가 시작되어 마찬가지로 정보를 못불러오고 안되더군요..
확인 부탁드립니다.

**Comment by wonipapa** [comment]
수정해봤습니다.
테스트 부탁드려요

**Comment by bgs2313** [comment]
시리즈 정보 회차 못받아 오는 문제 수정 버전 0.23에서는 정글의 법칙을 못불러오는군요

0.22로 낮추어서 하니 겟 잇 뷰티 시즌 13[2019]와 선을 넘는 녀석들도 시즌 2 정상적으로 불러와졌구요
좀오래걸렸지만 정글의 법칙 전부 다시 불러오는데 성공하였습니다.
변수만 변경한 버전은 성공하였으나 0.23으로 최종으로 올려주신 버젼은 몇번 로딩 서클 돌다 그냥 이후 작업이 없네요..
변수 오류 수정 버전으로 일단 사용하겠습니다.

PLEX 버전은 1.15.1.707입니다. 
시놀 1515+사용중이구요..

**Comment by wonipapa** [comment]
새로운 버전으로 게잇뷰티는 잘 작동됩니다.
