### ISSUE TITLE
tv 시리즈 정보 못불러오는게 몇 개 있습니다

### ISSUE THREAD

**Issue by lovjiyun** [wonipapa/DaumMovieTVSeries.bundle#11]
일단 감사 말씀 먼저 드리겠습니다. 수고스럽겠지만 업데이트 부탁드립니다.
12시간 전 새로 배포해주신 걸로 적용해봤는데요. 대부분 잘 정보를 받아오는데 일부 몇 개 프로그램에서 못 가져오는 문제가 있었습니다.
현재 가져오는데 문제 있는 쇼는 "출발! 비디오 여행", "미추리 8-1000" 입니다. 미리 감사말씀드리겠습니다. 잘 부탁드립니다.
plex 버전 : 1.14.1.5488

**Comment by wonipapa** [comment]
원인은 뭔지 찾았습니다.
수정해보도록 하겠습니다.

**Comment by bgs2313** [comment]
최신으로 업데이트후 김병만의 정글의 법칙을 못불러 오고있습니다.
예전에 알려주신대로 시즌만 바꾸고 시리즈 넘버는 계속 증가하며 사용중이고
이번에 시즌 40되면서 시리즈 정보 자체를 못불러 오고 있습니다.
확인 부탁드려요
추가로 계속 여러가지 시즌을 돌아가면서 스캔하다보니 불러오는경우도 생기긴 하는것같습니다.
시즌이 너무 많아서 그런것인지 ? 잘모르겠으나 일단은 불러와졌습니다.
plex 버전 1.15.1.710

**Comment by wonipapa** [comment]
정글의 법칙은 왜 안되는지 이유는 알겠네요. 원인은 알았는데 어떻게 고칠지는 고민좀 해보겠습니다.
