### ISSUE TITLE
PLEX 1.16.4.1469업데이트후 

### ISSUE THREAD

**Issue by bgs2313** [wonipapa/DaumMovieTVSeries.bundle#15]
PLEX 1.16.4.1469업데이트후  
영화에서 에이전트 검색 가능
TV 쇼에서는 에이전트가 사라짐
다른 에이전트 들은 업데이트 후에도 영화와 TV 쇼에서 둘다 사용가능합니다
TV 쇼에서도 사용가능하게 부탁드립니다.

**Comment by wonipapa** [comment]
확인해보겠습니다
