### ISSUE TITLE
어서와 한국은 처음이지? 확인 부탁드려요

### ISSUE THREAD

**Issue by bgs2313** [wonipapa/DaumMovieTVSeries.bundle#16]
안녕하세요~ 오랜만에 Issues 적어봅니다.
어서와 한국은 처음이지?를 에이전트 적용하여 잘사용중인데
시즌과 에피소드가 나뉘어서 있어 아래와 같이 네임 정의하여 사용중입니다.
시즌1
어서와~ 한국은 처음이지？.S01.E001~어서와~ 한국은 처음이지？.S01.E033
시즌2
어서와~ 한국은 처음이지？.S01.E034~어서와~ 한국은 처음이지？.S01.E098
까지는 정상적으로 에피소드및 회차가 잘불러와 집니다.
그런데 99화 부터 현재 108화는 에피소드를 못불러오는데 왜 그런것일까요?
확인 부탁드려요

**Comment by bgs2313** [comment]
VERSION = '0.26'에서는 메타파일 다시 고침 2번하니 모든 데이터를 읽어오는데
VERSION = '0.27'에서는 정보자체를 못읽어올경우도 있습니다.
무엇이 문제인지는 정확히 모르겠네요...

**Comment by wonipapa** [comment]
어서와 한국이지는 시즌이 두개로 나누어져야 작동할 겁니다.
S02E098 이런식으로 해주셔야 될겁니다.

**Comment by bgs2313** [comment]
드디어 해결 했습니다.
폴더와 파일명에 ￦／：＊？″＜＞｜문자를 사용하여 그렇게 된것같습니다.
실제 키보드의 키 \/:*?"<>|와는 다르게 파일 및 폴더에도 적용할수 있는 문자이며
윈도우에서 어서와 한국은 처음이지？으로 폴더 및 파일명을 만들었다가 
？를 삭제하니 잘읽어오게 되었습니다.

잘이해가 안가실수도 있는데 원래 폴더나 파일명에는 \/:*?"<>|문자를 못쓰게되어있으나 
특수문자로 삽입하면 폴더나 파일 명에 ￦／：＊？″＜＞｜로 내용을 적을수 있었기에 발생한 경우입니다.
