### ISSUE TITLE
오랜만에 다음 영화 검색 사이트가 업데이트 되었습니다.

### ISSUE THREAD

**Issue by bgs2313** [wonipapa/DaumMovieTVSeries.bundle#19]
새해 복많이 받으세요
오랜만에 이슈 올립니다.
오랜만에 다음 영화 검색 사이트가 업데이트 되었습니다.
TV 쇼는 검색이 잘되지만 영화는 검색이 안되어서 글올립니다.

**Comment by gremma** [comment]
> 새해 복많이 받으세요
> 오랜만에 이슈 올립니다.
> 오랜만에 다음 영화 검색 사이트가 업데이트 되었습니다.
> TV 쇼는 검색이 잘되지만 영화는 검색이 안되어서 글올립니다.

이 번들은 신경 못 쓰시고 계신것 같습니다.

https://github.com/axfree/DaumMovie.bundle 에서 내려받으세요.

**Comment by wonipapa** [comment]
제가 직장을 옮기면서 많이 신경을 못쓰고 있었네요. 이번주말정도에 수정을 하도록 하겠습니다.
감사합니다.

**Comment by wonipapa** [comment]
수정해서 올려놨습니다.
