### ISSUE TITLE
드라마 시즌오류

### ISSUE THREAD

**Issue by airbogo** [wonipapa/DaumMovieTVSeries.bundle#2]
특정 한국 드라마 시즌2 를 등록해도 메타정보는  시즌1으로 강제 등록이 되는군요.. 특이한 현상이라 당황스럽습니다. 파일명은 " 제목 시즌2.E01 " 보통 이렇게 사용하거든요

**Comment by airbogo** [comment]
아 이버전은 파일명을 시즌별로 관리를 다시 해야되는거군요

**Comment by wonipapa** [comment]
시리즈가 되는 거라서 그렇습니다.
플랙스가 시즌은 S01E01 이런식이거든요.
