### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by airbogo** [wonipapa/DaumMovieTVSeries.bundle#3]
영화메타정보를 불러오긴 하는데 포스터를 제대로 못불러오는 현상이 있는것 같습니다.
이것때문에 다른번들 사용하다가 넘어왔는데 똑같은 증상이 또 발생되네요 plex move로 검색해보면 포스터 다 정상으로 불러와 지는데 daum 번들 사용하면 메인포스터가 안불러 와지네요 불러온 포스터를 선택하더라도 선택이 안되는 현상도 있구요 특이한 현상이라 설명하기가 쉽지가 않네요

**Comment by wonipapa** [comment]
안되는 영화 제목 알려주시면 한번 확인은 해보겠습니다.

**Comment by airbogo** [comment]
일단 지금은 또 잘 되는것 같아요 왜 그랬는지 잘 이해가 안되지만 더 확인해볼고 문제가 재현 되면 말씀드릴게요 바쁘실텐데 답변 주셔서 감사합니다.
