### ISSUE TITLE
타이틀에 ); 이 들어가 있는 경우가 있습니다.

### ISSUE THREAD

**Issue by soju6jan** [wonipapa/DaumMovieTVSeries.bundle#4]
작은 신의 아이들 메타가 안 떠서 봤더니 에피소드 타이틀에 ); 이 들어가 있네요 ;;;;
예) "title" : "초혼(招魂); 죽은 자를 '부르다'",
  "title" : "무령(巫鈴); 방울이 '울다'",

] 넣어서 하면 불러오긴 하는데 아름답지가 않네요 ㅋ
match = Regex('MoreView\.init\(\d+, (.*?)\]\);', Regex.DOTALL).search(episodepage.content)
episode_json_data = JSON.ObjectFromString(match.group(1) + ']', max_size = JSON_MAX_SIZE)

항상 잘 사용하고 있습니다!!! 감사합니다~

**Comment by wonipapa** [comment]
4일전에 올린게 작은신의 아이들 수정한 버전입니다.
저는 잘되는데 테스트 해보시고 피드백 주세요.

**Comment by soju6jan** [comment]
네.. 잘됩니다. 감사합니다~
