### ISSUE TITLE
json을 이용한 id 직접 지정

### ISSUE THREAD

**Issue by Nova-Kim** [wonipapa/DaumMovieTVSeries.bundle#5]
json으로 메타데이터 재정의가 가능하게 만들어주신 김에, json에 다음 tv쇼와 무비 id를 지정하는 기능을 추가해 주셨으면 하고 바라봅니다. daum-tv-id와 daum-movie-id를 지정하면 검색 과정 없이 바로 해당 데이터를 가져올 수 있도록요. 다음 데이터가 동일 이름 처리가 매우 취약하더라구요. 특히 영화 같은 경우 흔한 단어로 이루어진 짧은 제목은 수동 매칭이 필요하니 아예 json으로 id를 지정할 수 있으면 편할 것 같습니다.

바쁜 시간 내셔서 좋은 프로그램 만들어주신 것, 언제나 감사드리고 있습니다~!

**Comment by wonipapa** [comment]
제가 영화는 json을 쓸 필요가 없어서 안만들었는데 그것도 해봐야겠네요.아이디는 고려해보겠습니다
