### ISSUE TITLE
배우 정보를 가져오지 못함

### ISSUE THREAD

**Issue by Nova-Kim** [wonipapa/DaumMovieTVSeries.bundle#6]
plex 서버가 두 대인데 이번 다음 TV 개편 전에 wonipapa님 에이전트로 스크랩한 녀석들은 배우 정보를 가지고 있습니다. 테스트용 서버에서 에이전트를 업데이트한 후 새로 스크랩한 녀석들은 배우 정보가 없네요. 혹시나 싶어서 운영 서버에서 에이전트를 업데이트한 후 이전에 스크랩한 녀석들을 메타데이터 새로 고침해 보니 배우 정보가 사라집니다. 시간 나시면 확인 부탁드립니다~

**Comment by wonipapa** [comment]
확인해보겠습니다.
