### ISSUE TITLE
json파일 생성 후 폴더에 위치 했으나 메타데이터 읽지 못함

### ISSUE THREAD

**Issue by towhereur** [wonipapa/DaumMovieTVSeries.bundle#7]
비긴어게인 2의 메타데이터를 읽지 못해 wonipapa님이 만드신 daumjson.php  로 비긴어게인 2.json파일 생성했습니다.
생성한 json 파일을 비긴어게인 2 폴더에 위치하였고, Plex상에는 Daum Movie TV Series 로 Agent를 설정 후 메타데이터 새로고침을 하였으나 정보를 읽지 못하네요.

Plex는 최신버전입니다. 3.57.1

참고로 OS는 Mac mini 입니다.

**Comment by wonipapa** [comment]
Info.plist 파일을 제가 업데이트를 안했네요.
현재 올려준 파일로 업데이트 해주세요.
업데이트 후 플랙스 재시작 하시면 반영될겁니다.
