### ISSUE TITLE
수정해주신 번들 적용이 안되고있습니다.

### ISSUE THREAD

**Issue by bgs2313** [wonipapa/DaumMovieTVSeries.bundle#8]
수정해주신 번들 적용이 안되고있습니다.
11일 임시패치 때부터 계속 시도 해보고 있으나 
그전에는 잘되던것이 적용이 안되는데 아직 작업중이신건가요?
아님 다른 조치를 해야하는것인지요?

**Comment by wonipapa** [comment]
현재 제가 사용중인 버전이 올라가 있는 상태입니다. 아직까지는 버그는 없는 것 같습니다만.. 확인해보겠습니다.

**Comment by Nova-Kim** [comment]
고생하셨습니다. 수정 감사합니다!
저도 테스트해봤습니다. 폴더 이름은 '만원 (2018)', '악마가 와서 피리를 분다 (2018)', '무인 토시이에 (2002)'입니다. 셋 모두 정보를 가져오지 못합니다. plex에서 '일치 항목 수정'을 선택하면 대상 항목이 정확히 검색되어 뜹니다만, 선택하면 정보를 가져오지 못하네요.

**Comment by ssampaq** [comment]
드라마나 쇼프로가 적용이 잘되시나요?
방금 다운로드해서 적용해보니 메타데이타를 가져오지못하는데… 제가 잘못하는건가요?
늘 감사하게 사용중입니다.

**Comment by davinci0101** [comment]
덕분에 Plex Life를 잘 즐기고 있습니다. 감사드립니다. ^^

오늘 기쁜 마음으로 새버전을 다운로드 하였습니다만
윗분 들처럼 여전히 드라마의 메타정보를 가져오지 못하는 것 같습니다. 

워니파파님은 이상이 없으신지요?

**Comment by wonipapa** [comment]
4분이나 안되신다고 하는데 어제 올린 버전이 현재 제가 쓰는 버전인데 문제를 모르겠네요.
에피소드별 메타데이터는 좀 늦게 가져올 수 있습니다. 다음에서 에피소드별로 개별페이지를 가지게 해서 가져오는 시간에 여유를 두게 했습니다.
제가 쓰는 플렉스 버전은 1.13.5.5332 입니다.
문제가 있다면 로그폴더 (저는 /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/)의 com.plexapp.agents.daum_tv_series.log  로그를 첨부해주시면 수정하는데 도움이 될 것습니다.

**Comment by ssampaq** [comment]
윈도우에 plex server를 설치해서 사용중인데 log파일이 어디 있는지 모르겠네요.
버전은 1.13.5.5332 입니다
몇몇 메다데이타 스크래퍼를 사용했지만 전 wonipapa님껄 더 애용합니다.
에피소드 소제목까지 표시해주는게 너무 맘에 들었습니다.
[com.plexapp.agents.daum_tv_series.log](https://github.com/wonipapa/DaumMovieTVSeries.bundle/files/2395463/com.plexapp.agents.daum_tv_series.log)

현재 다른분 스크래퍼를 사용중인데 ....

**Comment by wonipapa** [comment]
Info.plist 파일 업데이트 해주세요.
 파일을 저만 업데이트 하고 반영을 안했네요.


> 윈도우에 plex server를 설치해서 사용중인데 log파일이 어디 있는지 모르겠네요.
> 버전은 1.13.5.5332 입니다
> 몇몇 메다데이타 스크래퍼를 사용했지만 전 wonipapa님껄 더 애용합니다.
> 에피소드 소제목까지 표시해주는게 너무 맘에 들었습니다.
> [com.plexapp.agents.daum_tv_series.log](https://github.com/wonipapa/DaumMovieTVSeries.bundle/files/2395463/com.plexapp.agents.daum_tv_series.log)
> 
> 현재 다른분 스크래퍼를 사용중인데 ....

**Comment by wonipapa** [comment]
Info.plist 파일 새로 받아서 덮어써주세요.
업데이트 후 플랙스 재시작 하시면 반영될겁니다.

**Comment by bgs2313** [comment]
업데이트 하고 적용하니 이상없이 동작합니다.
그런데 시리즈물에 적용하니 예를 들어
풀 뜯어먹는 소리 를 적용하니

풀 뜯어먹는 소리
풀 뜯어먹는 소리 - 가을편

위에 두 항목이 검색되며
기존에는 어느것을 선택 하던 [풀 뜯어먹는 소리]로  메인 제목이 설정 되었습니다.
그러나 이번에는 [풀 뜯어먹는 소리 - 가을편]으로메인 제목이 설정되며
포스터 또한 [풀 뜯어먹는 소리 - 가을편]의 포스터가 선택이 되네요
포스터는 첫번째 시즌 또는 사용자가 직접 선택할수 있으면 좋을듯 합니다.

**Comment by wonipapa** [comment]
다음 사이트 변경전에는 시리즈 통합 제목이 존재했는데 이제는 그게 없어졌습니다.
그래서 궁여지책으로  시리즈의 최신 제목과 포스터가 반영되게 했습니다
제목의 경우 수작업으로 변경후 자물쇠 버튼으로 잠그면 변형이 안될겁니다.
포스터의 경우 시리즈의 것 모두 가져오는게 사실 가능하긴 합니다. 그 중 하나를 선택하게 하는 방안도 고민해보겠습니다.

> 업데이트 하고 적용하니 이상없이 동작합니다.
> 그런데 시리즈물에 적용하니 예를 들어
> 풀 뜯어먹는 소리 를 적용하니
> 
> 풀 뜯어먹는 소리
> 풀 뜯어먹는 소리 - 가을편
> 
> 위에 두 항목이 검색되며
> 기존에는 어느것을 선택 하던 [풀 뜯어먹는 소리]로 메인 제목이 설정 되었습니다.
> 그러나 이번에는 [풀 뜯어먹는 소리 - 가을편]으로메인 제목이 설정되며
> 포스터 또한 [풀 뜯어먹는 소리 - 가을편]의 포스터가 선택이 되네요
> 포스터는 첫번째 시즌 또는 사용자가 직접 선택할수 있으면 좋을듯 합니다.

**Comment by bgs2313** [comment]
고민 감사합니다. 
복수노트에 적용해보았습니다.
전에 사용작성하여 사용했던 시즌1에는 복수노트 시즌1 (2017)[웹드라마].json을 넣었고
시즌2는 없이 그냥 불러왔으나 
시즌1은 하나도 적용이 안되었으며
시즌2는 에피소드가 현재 12개까지 나와있으나 에피소드 7까지만 적용되고 나머지8~12는 적용이 되지 않고 있네요...

**Comment by wonipapa** [comment]
복수노트 시즌 1의 다음 데이터가 문제가 있네요.  에러처리를 추가해야 겠습니다. 집에 가면 수정하도록 하겠습니다. 



> 복수노트에 적용해보았습니다.
> 시즌1에는 복수노트 시즌1 (2017)[웹드라마].json을 넣었고
> 시즌2는 없이 그냥 불러왔으나
> 시즌1은 하나도 적용이 안되었으며
> 시즌2는 에피소드가 현재 12개까지 나와있으나 에피소드 7까지만 적용되고 나머지8~12는 적용이 되지 않고 있네요...

**Comment by davinci0101** [comment]
info.plist 수정하니 제대로 동작하는 듯해 보입니다.
참고로 저는 json은 사용하지 않고 있습니다.

다음 개편 이후로 그동안 저에게는 2가지 tv 시리즈가 추가되었는데 하나가 제대로 동작하지 않습니다.

"마블 아이언 피스트 시즌2" 로 검색하면 검색은 되지만 메타정보를 여전히 가져오지는 못합니다.
혹시 퇴근하신다면 이부분도 확인 부탁드립니다.

부탁만 드려 죄송하네요 .

**Comment by wonipapa** [comment]
> info.plist 수정하니 제대로 동작하는 듯해 보입니다.
> 참고로 저는 json은 사용하지 않고 있습니다.
> 
> 다음 개편 이후로 그동안 저에게는 2가지 tv 시리즈가 추가되었는데 하나가 제대로 동작하지 않습니다.
> 
> "마블 아이언 피스트 시즌2" 로 검색하면 검색은 되지만 메타정보를 여전히 가져오지는 못합니다.
> 혹시 퇴근하신다면 이부분도 확인 부탁드립니다.
> 
> 부탁만 드려 죄송하네요 .
살펴보겠습니다.

**Comment by kor21027** [comment]
좋은 자료 올려주셔서  PLEX 잘 사용 중입니다. 정보 잘 불러오는데 최신 회차 정보를 불러오지 못합니다. 뭐가 잘못된걸까요? 날짜 상관없이 프로그램별로 최신회차는 정보가 안나오네요. 참고로 다큐멘터리들이며 에피소드는 날짜로 매칭시켜놨습니다.

**Comment by wonipapa** [comment]
> > info.plist 수정하니 제대로 동작하는 듯해 보입니다.
> > 참고로 저는 json은 사용하지 않고 있습니다.
> > 다음 개편 이후로 그동안 저에게는 2가지 tv 시리즈가 추가되었는데 하나가 제대로 동작하지 않습니다.
> > "마블 아이언 피스트 시즌2" 로 검색하면 검색은 되지만 메타정보를 여전히 가져오지는 못합니다.
> > 혹시 퇴근하신다면 이부분도 확인 부탁드립니다.
> > 부탁만 드려 죄송하네요 .
> > 살펴보겠습니다.

수정해서 올렸습니다.

**Comment by ssampaq** [comment]
감사합니다. 오늘 새로 올라온파일로 교체후 잘 작동합니다.
간혹, 특정프로(예, 꽃보다 할배 리턴즈)에서 엉뚱하게 꽃보다 할배 유럽, 대만 2013 메타정보를 가져옵니다.
이런부분때문에 JSON파일을 사용해보려고 하는데 윈도우에서는 사용할수없나요?
늘 감사하게 생각하면 사용중입니다. 고맙습니다.
ps. 방금 확인한 결과 다른 스크래퍼는 정상적으로 메타데이타를 받아오는걸 확인했습니다. 참고 부탁드립니다

**Comment by wonipapa** [comment]
꽃할배 리턴즈는 시리즈로 보면 4번째 시즌입니다. 파일명에 S04E01 형식으로 들어가 있어야 합니다. S01E01이 파일명에 들어가 있다면 시즌1으로 인식해서 대만정보를 가져오는 겁니다.
json 파일은 만들기만 하면 윈도우에서도 사용은 가능할 겁니다. 윈도우에서 만드는 방법을 말하는 건지요?

**Comment by ssampaq** [comment]
빠른 답변 감사합니다.
윈도우에서 json파일을 만드는 방법을 알고싶습니다.
꽃보다 할배는 시즌정보없이 E01 이렇게만 모았는데 시즌정보를 다 넣어야 하는군요.
답변 감사합니다.
그리고 소제목이 없는 에피소드는 날짜 정보가 나오는게 더 보기 좋을듯합니다만...
또 한가지는 현재 공유되고있는 파일명(회차가없는 영상 예, 뉴스, 다큐멘타리등)의 날짜들이 180920 이렇게 되어있는걸 2018-09-20 이렇게 변경해서 사용중입니다. 이부분은 파일명을 수정하지않은채로 사용할수있는 방법은 없습니까?
 늘 부탁만 드려서 죄송한맘입니다.

**Comment by wonipapa** [comment]
윈도우용 php 설치하면 되긴 할겁니다. 현재 제 리포지터리에 있는 다음용 json 만들기는 다음 개편에  따른 내용 반영을 아직 안했습니다. 일단 이쪽 부분 버그 등 있는 것 찾아서 손보고 고칠 예정입니다.

**Comment by Nova-Kim** [comment]
정말 고생하셨습니다. json과 결합하면 완벽한 관리가 가능하겠습니다. 정말 감사합니다.

**Comment by bgs2313** [comment]
너무 고생하신것 정말 감사드립니다.
추가 이슈 사항이있습니다.
예를 들어 마블 제시가 존스, 마블 데어데블에 적용을 해보았습니다.
각각 제가 가지고 있는 시즌은 시즌1, 시즌2 를 가지고있습니다.
메타데이터 적용을 하면 포스터가 시즌1을 맞게 적용됩니다. 하지만 시즌2에는 다음에서 검색된 시즌3에 포스터가 적용이 되는군요. 확인 부탁드립니다.
질문한가지 드립니다. 메타 데이터 불러오는데 시간이 좀 많이 걸리는것이 맞는지요?
확인부탁드립니다.

**Comment by wonipapa** [comment]
> 너무 고생하신것 정말 감사드립니다.
> 추가 이슈 사항이있습니다.
> 예를 들어 마블 제시가 존스, 마블 데어데블에 적용을 해보았습니다.
> 각각 제가 가지고 있는 시즌은 시즌1, 시즌2 를 가지고있습니다.
> 메타데이터 적용을 하면 포스터가 시즌1을 맞게 적용됩니다. 하지만 시즌2에는 다음에서 검색된 시즌3에 포스터가 적용이 되는군요. 확인 부탁드립니다.
> 질문한가지 드립니다. 메타 데이터 불러오는데 시간이 좀 많이 걸리는것이 맞는지요?
> 확인부탁드립니다.

예. 어쩔 수 없습니다. 이전에는 에피소드를 한번에 가져올 수 있었는데 개편된 사이트는 에피소드별로 페지가 구성되어 있어서 시간이 좀 걸립니다.
오늘 올린 파일은 그 부분을 좀 더 최적화 했습니다.
알려주신 문제는 참고해서 고쳐보겠습니다.
