### ISSUE TITLE
시즌이 잘 나타나지 않아요..

### ISSUE THREAD

**Issue by myhappyhouse** [wonipapa/DaumMovieTVSeries.bundle#9]
올려주신 에이전트 잘 사용하고 있습니다.. 감사합니다. ^^
헌데 저는 시즌에 대한 정보가 잘 동작하지 않는 것 같은데요..

전 시즌을 그냥 아래처럼 폴더채로 관리하고 있엇는데요.
예를 들어 헬로XX 이라고 하면

- 헬로XX 시즌1
- 헬로XX 시즌2
- 헬로XX 시즌3
...
...

이렇게 폴더를 설정하고 헬로XX를 검색해서 나오는
- 헬로XX 1
- 헬로XX 2
- 헬로XX 3

를 선택하면 잘 나왔었는데..

이제는 설사 검색해서 나온 헬로XX 3을 선택해도..
시즌에 상관없이 무조건 시즌1으로만 정보가 나타나고 있습니다. ㅠ.ㅠ.

혹시 폴더 경로가 맞지 않아서 그런가 해서..
- 헬로XX
   - 시즌1
   - 시즌2
   - 시즌3

으로 폴더 안에 넣었더니.
이제는 시즌3은 잘 나타나는데.. 시즌2는 역시 시즌1의 정보가 그대로 나타나네요.

혹 설정상의 문제일까요?

**Comment by bgs2313** [comment]
진짜 사나이를 적용해보았습니다.
바로 적용이 안되고 늦게 적용이 됩니다
처음은 안되는줄알았습니다..

시간이 걸좀 걸리네요 윈도우 버전에서는 적용되었습니다.
시놀에서 시험해보고 있습니다.
시놀은 생각보다 더 오래 걸리는듯합니다.

Troubleshooting항목이 생겼던데 그것을 한번 적용해보셔도 ,,,,,
다음에서 가져오는데 시간이 더욱 걸려서 그러는것같기도 합니다.

시놀에서는 한번에 적용은 안되고 여러번 반복하니 적용되었습니다.

**Comment by ssampaq** [comment]
섬총사 시즌2 같은경우엔 회차랑 날짜가 안맞게 나옵니다.
다른 스크래퍼를 사용하면 정상적으로 회차랑 정보가 맞습니다.
언제나 감사하게 사용중입니다. 고생 많으십니다.

**Comment by wonipapa** [comment]
> 섬총사 시즌2 같은경우엔 회차랑 날짜가 안맞게 나옵니다.
> 다른 스크래퍼를 사용하면 정상적으로 회차랑 정보가 맞습니다.
> 언제나 감사하게 사용중입니다. 고생 많으십니다.

섬총사 지금 테스트 해봤는데 잘 됩니다. 이전버전에 그런 문제가 있어서 수정했으니 다시 받아서 적용해보세요.

**Comment by bgs2313** [comment]
정글의 법칙 1~38기까지 포스터는 잘적용되는데 내용은 하나도 적용이 되지를 않습니다.
불일치로하였다가 다른시즌으로 적용하여도 전체 포스터는 잘적용되나 시즌 내용은 시즌1만 적용됨을 확인하였습니다.

KBS드라마스페셜또한 포스터는 적용되나 내용이 없습니다.

**Comment by wonipapa** [comment]
> 정글의 법칙 1~38기까지 포스터는 잘적용되는데 내용은 하나도 적용이 되지를 않습니다.
> 불일치로하였다가 다른시즌으로 적용하여도 전체 포스터는 잘적용되나 시즌 내용은 시즌1만 적용됨을 확인하였습니다.
> 
> KBS드라마스페셜또한 포스터는 적용되나 내용이 없습니다.
정글의 법칙은 시즌은 나뉘어져 있는데 회차는 이어집니다.
S01E11 로 1시즌이 끝나면 시즌2는 S02E12로 이어지는 식입니다.
확인바랍니다.
그리고 드라마스페셜은 회차정보가 없고 코너정보로 되어 있어서 다루기가 좀 힘듭니다.

**Comment by bgs2313** [comment]
네 잘알겠습니다.
소드 아트 온라인 얼터너티브 건 게일 온라인을 매칭중 5.5항목이있습니다.
1~5까진 잘 불러와지는데 중간에 5.5항목 이후로는 안불러와집니다.
소드아트 온라인1기,2기는 시리즈로 잘정리 되어 2기에서 14.5화는 15화, 그이후로 변경하여 설정하여 잘매칭되었는데 소드 아트 온라인 얼터너티브 건 게일 온라인을 매칭중 5까지 에피소드 매칭만되고 그후로는 안되더군요
최근에 https://github.com/axfree/DaumMovie.bundle의 번들을 적용하니 5.5항목이 매칭이 안되더군요
다시 DaumMovieTVSeries.bundle로 적용하니 DaumMovie.bundle에서 적용되었던 날짜 정보는 남아있는데 에피소드 제목들은 없어지더군요 확인 부탁드립니다.
